PREFIX pub: <http://www.example.edu/publication/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT distinct ?sub
WHERE {
    ?sub rdf:type pub:author.
}


PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX pub: <http://www.example.edu/publication/>
SELECT distinct ?sub
WHERE {
    ?sub rdfs:domain pub:author 
}


PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX pub: <http://www.example.edu/publication/>
SELECT distinct ?sub
WHERE {
    {
        ?sub rdfs:domain pub:conference 
    }
    union 
    {
        ?sub rdfs:domain pub:workshop 
    }
}




PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX pub: <http://www.example.edu/publication/>
SELECT ?paper_title ?author_name
WHERE {
	?paper pub:title ?paper_title .
    ?paper pub:written_by/pub:author_name ?author_name .
    ?conference ^pub:conf_name/^pub:conf_edition_rel/pub:conf_edition_paper_rel ?paper .
    FILTER(?author_name='Rianne van den Berg')
}



# All conferences with number of papers published in it and provide result in decreasing order of number of publications 
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX pub: <http://www.example.edu/publication/>
SELECT ?conf_name (count(distinct(?paper)) AS ?publication_count)
WHERE {
    ?conference pub:conf_name ?conf_name .
    ?conference ^pub:conf_edition_rel/pub:conf_edition_paper_rel ?paper
}
GROUP BY ?conf_name
ORDER BY DESC(?publication_count)



# All reviewers sho reviewed more than 7 papers related to database
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX pub: <http://www.example.edu/publication/>
SELECT ?reviewer (COUNT(?paper) AS ?cnt_paper)
WHERE {
    ?paper ^pub:paper_reviewer_rel/pub:reviewed_by/pub:reviewer_name ?reviewer .
    ?paper pub:contains/pub:keyword_name ?keyword .
    FILTER(CONTAINS(LCASE(?keyword), "data"))
}
GROUP BY ?reviewer
HAVING (?cnt_paper>=7)