# Number of classes
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX pub: <http://www.example.edu/publication/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT  (COUNT(DISTINCT ?class) AS ?num_classes)
WHERE {
    ?class rdf:type rdfs:Class
}

# Number of property 
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX pub: <http://www.example.edu/publication/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT  (COUNT(DISTINCT ?prop) AS ?num_prop)
WHERE {
    ?prop rdf:type rdf:Property
}


# Number of instances per class 
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX pub: <http://www.example.edu/publication/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT   ?class (count(?instance) as ?num_instance)
WHERE {
    ?instance rdf:type ?class 
}
group by ?class


# Number of triples for all properties 
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX pub: <http://www.example.edu/publication/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT   ?p (count(*) as ?num_triples)
WHERE {
    ?s ?p ?o .
        FILTER (?p IN (pub:title, pub:abstract, pub:citation_count, pub:publication_date, pub:author_id, pub:author_name, pub:org_id, pub:org_name, pub:org_type, pub:conf_id, pub:conf_name, pub:journal_id, pub:journal_name, pub:workshop_id, pub:workshop_name))
}
group by ?p


PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX pub: <http://www.example.edu/publication/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT   ?p (count(*) as ?num_triples)
WHERE {
    ?s ?p ?o .
       ?p  rdf:type rdf:Property
}
group by ?p
