PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX pub: <http://www.example.edu/publication/>

CONSTRUCT {
    # 1. Define class (All nodes to defined as classes)
    pub:Keyword 		rdf:type 	rdfs:Class .
    pub:Paper 			rdf:type 	rdfs:Class .
    pub:Author 			rdf:type 	rdfs:Class .
    pub:Conference 		rdf:type 	rdfs:Class .
    pub:Workshop 		rdf:type 	rdfs:Class .
    pub:Journal 		rdf:type 	rdfs:Class .
    pub:Organization 	rdf:type 	rdfs:Class .
    
    
    # 2. Define super class if needed
    pub:Person 			rdf:type 	rdfs:Class .
    
    # 3. Define relation between subclass and superclass
    pub:Author 			rdf:subClassOf 	rdfs:Person .
    
    
    # 4. If there are some edges which contain properties, define them as Class
    pub:paper_review 		rdf:type 	rdfs:Class .
    pub:paper_writer 		rdf:type 	rdfs:Class .
    pub:conf_publication 	rdf:type 	rdfs:Class .
	pub:workshop_publication 	rdf:type 	rdfs:Class .
	pub:journal_publication 	rdf:type 	rdfs:Class .
    
	
    # Define properties (edges without property)
	pub:cites 			rdf:type 	rdfs:Property ;
    					rdfs:domain rdf:Paper ;
    					rdf:range 	rdf:Paper .

    pub:contains 		rdf:type 	rdfs:Property ;
    					rdfs:domain rdf:Paper ;
    					rdf:range 	rdf:Keyword .
    
    pub:affiliation 	rdf:type 	rdfs:Property ;
    					rdf:domain 	rdf:Author ;
    					rdf:range 	rdf:Organization .
    
	pub:corresponding_author 	rdf:type 	rdfs:Property ;
								rdf:domain 	rdf:Author ;
								rdf:range 	rdf:Paper .
	
	pub:writes	rdf:type 	rdfs:Property ;
				rdf:domain 	rdf:Author ;
				rdf:range 	rdf:Paper .
    
    # 5. Define data type property (Attributes of node)
    # Properties of Keyword 
    pub:keyword_name 	rdfs:domain 	pub:Keyword ;
        				rdfs:range 		xsd:String ;
        				rdf:type 		rdfs:Property .
    
    # Properties of Paper
    pub:paper_id 	rdfs:domain 	pub:Paper ;
        			rdfs:range 		xsd:String ;
        			rdf:type 		rdfs:Property .
    
	pub:title 		rdfs:domain 	pub:Paper ;
        			rdfs:range 		xsd:String	;
        			rdf:type 		rdfs:Property .
        
    pub:abstract 	rdfs:domain 	pub:Paper ;
        			rdfs:range 		xsd:String ;
        			rdf:type 		rdfs:Property .
        
    pub:citation_count 		rdfs:domain 	pub:Paper ;
        					rdfs:range 		xsd:integer;
        					rdf:type 		rdfs:Property .
        
    pub:publication_date 	rdfs:domain 	pub:Paper ;
        					rdfs:range 		xsd:date;
        					rdf:type 		rdfs:Property .
        
    
    # Properties of Author
	pub:author_id 			rdfs:domain 	pub:Author ;
        					rdfs:range 		xsd:String ;
        					rdf:type 		rdfs:Property .
        
    pub:author_name 		rdfs:domain 	pub:Author ;
        					rdfs:range 		xsd:String ;
        					rdf:type 		rdfs:Property .
        
    
    # Properties of Organization
	pub:org_id 				rdfs:domain 	pub:Organization ;
        					rdfs:range 		xsd:int ;
        					rdf:type 		rdfs:Property .

	pub:org_name 			rdfs:domain 	pub:Organization ;
        					rdfs:range 		xsd:String ;
        					rdf:type 		rdfs:Property .
        
	pub:org_type 			rdfs:domain 	pub:Organization ;
        					rdfs:range 		xsd:String ;
        					rdf:type 		rdfs:Property .
        
    # Properties of Conference
	pub:conf_id 			rdfs:domain 	pub:Conference ;
        					rdfs:range 		xsd:integer ;
        					rdf:type 		rdfs:Property .

	pub:conf_name 			rdfs:domain 	pub:Conference ;
        					rdfs:range 		xsd:String ;
        					rdf:type 		rdfs:Property .
    
    # Properties of Workshop
	pub:journal_id 			rdfs:domain 	pub:Journal ;
        					rdfs:range 		xsd:integer ;
        					rdf:type 		rdfs:Property .

    pub:journal_name 		rdfs:domain 	pub:Journal ;
        					rdfs:range 		xsd:String ;
        					rdf:type 		rdfs:Property .
    
    # Properties of Journal
	pub:workshop_id 		rdfs:domain 	pub:Workshop ;
        					rdfs:range 		xsd:integer ;
        					rdf:type 		rdfs:Property .

	pub:workshop_name 		rdfs:domain 	pub:Workshop ;
        					rdfs:range 		xsd:String ;
        					rdf:type 		rdfs:Property .
        
    
    # Define properties which are created because of edges having attributes
    pub:paper_reviewed 		rdfs:domain 	pub:paper_review ;
        					rdfs:range 		pub:Paper;
        					rdf:type 		rdfs:Property .

	pub:reviwer 			rdfs:domain 	pub:paper_review ;
        					rdfs:range 		pub:Author;
        					rdf:type 		rdfs:Property .

	pub:review_count 		rdfs:domain		pub:paper_review ;
            				rdfs:range		xsd:String ;
    						rdf:type 		rdfs:Property .
    
    pub:suggested_decision 	rdfs:domain		pub:paper_review ;
            				rdfs:range		xsd:String ;
    						rdf:type 		rdfs:Property .




        
	pub:conf_pub_conference 	rdfs:domain 	pub:conf_publication ;
        						rdfs:range 		pub:Conference;
        						rdf:type 		rdfs:Property .
	
	pub:conf_pub_paper		 	rdfs:domain 	pub:conf_publication ;
        						rdfs:range 		pub:Paper;
        						rdf:type 		rdfs:Property .

	pub:conf_pub_year 			rdfs:domain 	pub:conf_publication ;
        						rdfs:range 		xsd:INTEGER;
        						rdf:type 		rdfs:Property .
	
	pub:conf_pub_edition		rdfs:domain 	pub:conf_publication ;
        						rdfs:range 		xsd:INTEGER;
        						rdf:type 		rdfs:Property .



	pub:ws_pub_workshop	 		rdfs:domain 	pub:ws_publication ;
        						rdfs:range 		pub:Workshop;
        						rdf:type 		rdfs:Property .
	
	pub:ws_pub_paper		 	rdfs:domain 	pub:ws_publication ;
        						rdfs:range 		pub:Paper;
        						rdf:type 		rdfs:Property .

	pub:ws_pub_year 			rdfs:domain 	pub:ws_publication ;
        						rdfs:range 		xsd:INTEGER;
        						rdf:type 		rdfs:Property .
	
	pub:ws_pub_edition			rdfs:domain 	pub:ws_publication ;
        						rdfs:range 		xsd:INTEGER;
        						rdf:type 		rdfs:Property .		


	pub:jr_pub_workshop	 		rdfs:domain 	pub:jr_publication ;
        						rdfs:range 		pub:Journal;
        						rdf:type 		rdfs:Property .
	
	pub:jr_pub_paper		 	rdfs:domain 	pub:jr_publication ;
        						rdfs:range 		pub:Paper;
        						rdf:type 		rdfs:Property .

	pub:jr_pub_year 			rdfs:domain 	pub:jr_publication ;
        						rdfs:range 		xsd:INTEGER;
        						rdf:type 		rdfs:Property .
	
	pub:jr_pub_volume			rdfs:domain 	pub:jr_publication ;
        						rdfs:range 		xsd:INTEGER;
        						rdf:type 		rdfs:Property .	
}
WHERE {
}

