PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX pub: <http://www.example.edu/publication/>

CONSTRUCT {
    pub:keyword 		rdf:type 	rdfs:Class .
    pub:paper 			rdf:type 	rdfs:Class .
    pub:author 			rdf:type 	rdfs:Class .
    pub:conference 		rdf:type 	rdfs:Class .
    pub:workshop 		rdf:type 	rdfs:Class .
    pub:journal 		rdf:type 	rdfs:Class .
    pub:organization 	rdf:type 	rdfs:Class .
    pub:person 			rdf:type 	rdfs:Class .
    pub:author 			rdf:subClassOf 	rdfs:person .
     
    pub:paper_review 		rdf:type 	rdfs:Class .
    pub:paper_writer 		rdf:type 	rdfs:Class .
    pub:conf_publication 	rdf:type 	rdfs:Class .
	pub:workshop_publication 	rdf:type 	rdfs:Class .
	pub:journal_publication 	rdf:type 	rdfs:Class .
    
	pub:cites 			rdf:type 	rdfs:Property ;
    					rdfs:domain rdf:paper ;
    					rdf:range 	rdf:paper .

    pub:contains 		rdf:type 	rdfs:Property ;
    					rdfs:domain rdf:paper ;
    					rdf:range 	rdf:keyword .
    
    pub:affiliation 	rdf:type 	rdfs:Property ;
    					rdf:domain 	rdf:author ;
    					rdf:range 	rdf:organization .
    
	pub:corresponding_author 	rdf:type 	rdfs:Property ;
								rdf:domain 	rdf:author ;
								rdf:range 	rdf:paper .
	
	pub:writes	rdf:type 	rdfs:Property ;
				rdf:domain 	rdf:author ;
				rdf:range 	rdf:paper .
    
    pub:keyword_name 	rdfs:domain 	pub:keyword ;
        				rdfs:range 		xsd:String ;
        				rdf:type 		rdfs:Property .
    
    pub:paper_id 	rdfs:domain 	pub:paper ;
        			rdfs:range 		xsd:String ;
        			rdf:type 		rdfs:Property .
    
	pub:title 		rdfs:domain 	pub:paper ;
        			rdfs:range 		xsd:String	;
        			rdf:type 		rdfs:Property .
        
    pub:abstract 	rdfs:domain 	pub:paper ;
        			rdfs:range 		xsd:String ;
        			rdf:type 		rdfs:Property .
        
    pub:citation_count 		rdfs:domain 	pub:paper ;
        					rdfs:range 		xsd:integer;
        					rdf:type 		rdfs:Property .
        
    pub:publication_date 	rdfs:domain 	pub:paper ;
        					rdfs:range 		xsd:date;
        					rdf:type 		rdfs:Property .
        
	pub:author_id 			rdfs:domain 	pub:author ;
        					rdfs:range 		xsd:String ;
        					rdf:type 		rdfs:Property .
        
    pub:author_name 		rdfs:domain 	pub:author ;
        					rdfs:range 		xsd:String ;
        					rdf:type 		rdfs:Property .
        
	pub:org_id 				rdfs:domain 	pub:organization ;
        					rdfs:range 		xsd:int ;
        					rdf:type 		rdfs:Property .

	pub:org_name 			rdfs:domain 	pub:organization ;
        					rdfs:range 		xsd:String ;
        					rdf:type 		rdfs:Property .
        
	pub:org_type 			rdfs:domain 	pub:organization ;
        					rdfs:range 		xsd:String ;
        					rdf:type 		rdfs:Property .
        
	pub:conf_id 			rdfs:domain 	pub:conference ;
        					rdfs:range 		xsd:integer ;
        					rdf:type 		rdfs:Property .

	pub:conf_name 			rdfs:domain 	pub:conference ;
        					rdfs:range 		xsd:String ;
        					rdf:type 		rdfs:Property .
    
	pub:journal_id 			rdfs:domain 	pub:journal ;
        					rdfs:range 		xsd:integer ;
        					rdf:type 		rdfs:Property .

    pub:journal_name 		rdfs:domain 	pub:journal ;
        					rdfs:range 		xsd:String ;
        					rdf:type 		rdfs:Property .
    
	pub:workshop_id 		rdfs:domain 	pub:workshop ;
        					rdfs:range 		xsd:integer ;
        					rdf:type 		rdfs:Property .

	pub:workshop_name 		rdfs:domain 	pub:workshop ;
        					rdfs:range 		xsd:String ;
        					rdf:type 		rdfs:Property .
        
    pub:paper_reviewed 		rdfs:domain 	pub:paper_review ;
        					rdfs:range 		pub:paper;
        					rdf:type 		rdfs:Property .

	pub:reviwer 			rdfs:domain 	pub:paper_review ;
        					rdfs:range 		pub:author;
        					rdf:type 		rdfs:Property .

	pub:review_count 		rdfs:domain		pub:paper_review ;
            				rdfs:range		xsd:String ;
    						rdf:type 		rdfs:Property .
    
    pub:suggested_decision 	rdfs:domain		pub:paper_review ;
            				rdfs:range		xsd:String ;
    						rdf:type 		rdfs:Property .
        
	pub:conf_pub_conference 	rdfs:domain 	pub:conf_publication ;
        						rdfs:range 		pub:conference;
        						rdf:type 		rdfs:Property .
	
	pub:conf_pub_paper		 	rdfs:domain 	pub:conf_publication ;
        						rdfs:range 		pub:paper;
        						rdf:type 		rdfs:Property .

	pub:conf_pub_year 			rdfs:domain 	pub:conf_publication ;
        						rdfs:range 		xsd:integer;
        						rdf:type 		rdfs:Property .
	
	pub:conf_pub_edition		rdfs:domain 	pub:conf_publication ;
        						rdfs:range 		xsd:integer;
        						rdf:type 		rdfs:Property .

	pub:ws_pub_workshop	 		rdfs:domain 	pub:ws_publication ;
        						rdfs:range 		pub:workshop;
        						rdf:type 		rdfs:Property .
	
	pub:ws_pub_paper		 	rdfs:domain 	pub:ws_publication ;
        						rdfs:range 		pub:paper;
        						rdf:type 		rdfs:Property .

	pub:ws_pub_year 			rdfs:domain 	pub:ws_publication ;
        						rdfs:range 		xsd:integer;
        						rdf:type 		rdfs:Property .
	
	pub:ws_pub_edition			rdfs:domain 	pub:ws_publication ;
        						rdfs:range 		xsd:integer;
        						rdf:type 		rdfs:Property .		

	pub:jr_pub_workshop	 		rdfs:domain 	pub:jr_publication ;
        						rdfs:range 		pub:journal;
        						rdf:type 		rdfs:Property .
	
	pub:jr_pub_paper		 	rdfs:domain 	pub:jr_publication ;
        						rdfs:range 		pub:paper;
        						rdf:type 		rdfs:Property .

	pub:jr_pub_year 			rdfs:domain 	pub:jr_publication ;
        						rdfs:range 		xsd:integer;
        						rdf:type 		rdfs:Property .
	
	pub:jr_pub_volume			rdfs:domain 	pub:jr_publication ;
        						rdfs:range 		xsd:integer;
        						rdf:type 		rdfs:Property .	
}
WHERE {
}

